Unificacion ramas
InTechMOM/edvisto-mod-comparte-evalua-Back pull request #5
Opened 2023-11-22 22:08 UTC by Angiedylexx

1. Se agregó una descripción detallada del proyecto en la sección "Acerca del Proyecto".
2. Se caracteriza en su totalidad la identificación del proyecto, de su autora y los respectivos agradecimientos.
3. Se actualizó la tabla de contenido para reflejar los cambios realizados.
4. Se ampliaron las secciones de "Funcionalidades", "Base de datos y almacenamiento de datos", "Validación de Datos", "Documentación", "Construido con", "Usos", "Mapa de Ruta ", "Contribuidores", "Licencia", "Contactos" y "Agradecimientos". (Que irán siendo modificados a medida que se realice la construcción de las respectivas funcionalidades). 
5. Se incluye con detalle los prerequisitos e instalacion del repositorio de manera local.
6. Se agregaron enlaces y formatos para una mejor presentación, y se incluyeron imágenes ilustrativas.
7. Servidor
   - Se levanto el servidor en el puerto 3000.
8. Conexión de Base de Datos
   - Se estableció una conexión con la base de datos MongoDB para almacenar la información de usuario.
9. Modelos y Validación
   - Se estructuró el esquema de Mongoose para el modelo de usuario en MongoDB.
   - Se realizó la adecuada validación de los datos de entrada utilizando Joi para garantizar la integridad de los datos.
10. Configuración se Firebase
   - Se configuraron las credenciales de Firebase Auth con permisos de administración para autenticación de usuarios.
11. Desarrollo de las APIS 
    - `delete.js` para la eliminación de usuarios tanto en Firebase y MongoDB utilizando el id de la creación del usuario 
        suministrado por mongoDB.
    - `get.js` para obtener resultados filtrados por los diversos atributos considerados.
    - `post.js` para registrar nuevos usuarios en Firebase y MongoDB.
       a) Validación de Datos de Entrada
       b) Verificación de Email Único
       c) Comparación de Contraseñas
       d) Formato de Fecha de Nacimiento
       e) Registro en Firebase
       f) Creación de Usuario en MongoDB
       g) Respuesta Exitosa y envio de correo de verificación.
12. Manejo de errores por medio de un middleware simple
  - Se ha implementado una funcionalidad de manejo de errores en el servidor para garantizar que se gestionen 
     adecuadamente los errores del servidor.
13. Documentación 
   - Se proporciona documentación detallada para testear e integrar las API implementadas utilizando Swagger.
14. Actualización del README, según respecta a la funcionalidad
 
## Notas de revisión

La respectiva funcionalidad cuenta por la previa aprobación por la QA del equipo, a satisfacción y sin ningún bugs encontrado, como se evidencía en  [https://docs.google.com/spreadsheets/d/1PlUYf3LHScLtnm2AChgHEVIFw4hZejzKiX-NY5UlltI/edit?usp=sharing]

15. Se implementó la función de inicio de sesión que valida las credenciales del usuario y autentica con Firebase.
16. Se verifica la existencia del usuario en la base de datos y se controla el bloqueo de la cuenta después de 3 intentos fallidos.
17. Se reestablece el bloqueo de cuenta cuando el inicio de sesión es exitoso después de bloquearse.
18. Se implementó la función resetPassword que permite a los usuarios restablecer su contraseña si proporcionan una respuesta de seguridad correcta, previamente almacenada.
19. Si la respuesta de seguridad es correcta, se envía un correo electrónico de restablecimiento de contraseña (línea comentada).
20. Se actualiza el README, según el mapa de ruta.

Notas Adicionales:
Se realizarón las pertinentes pruebas unitarias, desde el backend utilizando como herramienta swagger, verificando y probando la lógica de las diversas funcionalidades y manejo de información tanto externo como interno para garantizar su correcto funcionamiento.
La funcionalidad de envío de correo electrónico de restablecimiento de contraseña se encuentra actualmente comentada y debe ser habilitada cuando sea necesario para su respectiva prueba. 

21. Se desarrolla la funcionalidad de registerGoogle que permite el registro e inicio de sesión de usuarios a través de Google. Se verifica el token de autenticación de Google y se guarda la información del usuario en MongoDB si es necesario (autenticación por primera vez).
22. Se desarrolla la función signOutUser que permite a los usuarios cerrar sesión manualmente.
23. Se actualiza README según corresponde

Pruebas Realizadas:
Se realizaron pruebas unitarias desde backend de la funcionalidad de registro (con información del IdToken), inicio de sesión y cierre de sesión manual, implementado una interfaz simulada y desarrollada con base a la documentación de Firebase .Se verificó que los usuarios se autentiquen correctamente a través de Google y se almacene su información en la base de datos MongoDB al igual que en la consola de firebase. También se verificó que los usuarios puedan cerrar sesión manualmente sin problemas.

Capturas de Pantalla:

**_REDIRECCIONAMIENTO PROVISIONAL_**
![Redireccionamiento provisional](https://github.com/InTechMOM/edvisto-mod-comparte-evalua-Back/assets/125603905/ddc06a09-6b69-44e4-93ed-8c4dcb512be2)

**_INTERFAZ SIMULADA_**
![Interfaz simulada](https://github.com/InTechMOM/edvisto-mod-comparte-evalua-Back/assets/125603905/9eba40f3-5a6c-466d-9c5c-ec7427bf50fa)

24. Creación y almacenamiento de la asignación en la base de datos, con limitación de fechas posteriores a la creación 
25. Obtención de proyectos según filtros opcionales en la consulta.
26. Búsqueda y eliminación de la asignación por ID.
27. Creación y almacenamiento de la entrega en la base de datos.
28. Actualización de la entrega con feedback y marcado como calificado.
29. Utilización de filtros como ID de asignación, correo del estudiante, correo, curso, título y calificación
30. Obtención del número de entregas calificadas y el total de entregas.

2023-11-27 18:48 UTC, marinellysfigueroa approved these changes
@KarenEchavarria, lo veo completo y bien estructurado, podría darle tu visto bueno también, gracias!!

2023-11-27 23:46 UTC, KarenEchavarria requested changes

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/assignment/routers/index.js
> +assignmentRouter.post("/project", assignment);
la ruta por convención REST debe ir en plural, entonces sería `/projects`. de la misma forma la ruta de `project/id` es el plural y te queda `projects/id`

Ojo con este cambio porque impacta en todo el sistema además de tu código, afecta las integraciones con front y otros equipos que estén usando tus APIS. La recomendación que te doy es para que lo aprendas, pero deberías discutir con tu equipo si es conveniente el cambio o no, dependiendo de quién esté usando la API actualmente.

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/feedback/controllers/get.js
> +    if (arrayDeliveries.length === 0) {
acá puedes hacer  `if(!arrayDeliveries?.length)` y estás validando lo mismo más la posibilidad de que te venga un `null` o un `undefined`

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/feedback/controllers/getCount.js
> +    if (!mongoose.isValidObjectId(id)) {
Esta validación de id se repite mucho y podrías sacarla en un archivo utils, hacera una función e importartela para reutilizarla en todos los lugares que se use tal cual. 

Lo anterior porque es mala práctica repetir código y las lineas que estas poniendo se repiten literalmente

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/feedback/controllers/getCount.js
> +    if (!mongoose.isValidObjectId(id)) {
acá tendrías que pasarte el `response `como parámetro para poder usar el `response.status ...`, si no te sale avisame y lo vemos

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/feedback/controllers/post.js
> +    if  (error.code === 11000) {
acá con el número 11000 también tienes otro magic number. Entiendo que haces referencia a un error de la base de datos. así que lo ideal es que pongas el nombre del error en una variable que permita entender a qué se refiere ese número

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/feedback/routers/index.js
> +deliveryRouter.post("/delivery/:id", delivery);
acá pasa igual con las rutas. Te dejo un articulo de rest que explica la estructura: https://juanda.gitbooks.io/webapps/content/api/arquitectura-api-rest.html#:~:text=Nombre%20de%20los%20recursos

Básicamente debe ir plural/idOReferenciaAlSingular/plural/singular y asi infinitamente. Es mala práctica mezclar singular unas rutas y plural otras. 

De nuevo, analiza con tu equipo y con Andre si dejan asi las rutas o si hacen la corrección.

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/users/controllers/authenticationGoogle.js
> +    console.log(idToken);
No deben quedar console.log en el código :P

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/users/controllers/get.js
> +    if (arrayUsers.length === 0) {
acá tambien puedes usar `!arrayUsers.length`

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/users/controllers/login.js
> +      console.log(user.blocked);
otro console.log salvaje

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/users/controllers/login.js
> +      if (rolWhich) {
acá puedes desanidar los ifs haciendo `if(rolwich && rolWhich.rol === "Soy Docente")`

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/users/controllers/login.js
> +        if (user.attemptsFailed === 3){
otro magic number acá

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/users/controllers/patch.js
> +  //await sendPasswordResetEmail(auth, email);
me parece que esta parte deberia estar descomentada :P

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/users/controllers/post.js
> +      //await sendEmailVerification(userFB); //Activar si se va a hacer prueba respectiva
Acá igual, si va la funcionalidad la debes descomentar, si no hay que borrarla

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/users/controllers/post.js
> +    if (dateParts.length === 3) {
Me parece que este código está literal en otra parte. Si es así, deberías hacer un util y reutilizar la funcion importandola en los dos lugares

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/users/controllers/post.js
> +      if (error.code === 11000 || error.keyPattern || error.keyValue) {
magic number

2023-11-27 23:46 UTC, KarenEchavarria commented on src/api/users/controllers/validation.js
> +let values_roles=["Soy Estudiante", "Soy Docente"]
Si `values_roles `y `values_securityQuestions` no cambian su valor, son constantes y no deberían estar declaradas con `let`, deberían estar con `const`

Ojo con las convenciones de nombres, en JS usamos el camelCase, también se usa para algunas variables especiales el snake_case. Lo que no se hace es mezcarlos como tu variable values_securityQuestions. Para mi debería ser camelCase.

2023-11-27 23:46 UTC, KarenEchavarria commented on src/models/user.js
> +  password: {
Hay algo importante, por lo que vi en tus controladores,no haces hasheo de la contraseña ni la encriptas de ninguna forma. Esto genera una vulnerabilidad de seguridad importante en cualquier sistema, porque nunca deberíamos guardar la contraseña en texto plano (es decir como nos llega) sino encriptada. 

una dependencia excelente para hacer esto es https://www.npmjs.com/package/bcrypt.

2023-11-29 00:55 UTC, Angiedylexx commented on src/models/user.js
> +  password: {
Se implementó Firebase authentication, por lo cual en este caso no lo utilice. Sin embargo lo tendre muy en cuenta para otros proyectos, :)

2023-12-04 20:02 UTC, closed without merging